//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 05:48:17 PM GMT 
//


package com.enterprise.process.web.service.processservice.impl;

import javax.xml.bind.annotation.XmlRegistry;
import com.enterprise.process.web.service.processservice.ClaimTaskRequest;
import com.enterprise.process.web.service.processservice.ClaimTaskResponse;
import com.enterprise.process.web.service.processservice.CompleteTaskRequest;
import com.enterprise.process.web.service.processservice.CompleteTaskResponse;
import com.enterprise.process.web.service.processservice.FetchUserTasksRequest;
import com.enterprise.process.web.service.processservice.FetchUserTasksResponse;
import com.enterprise.process.web.service.processservice.ParameterElement;
import com.enterprise.process.web.service.processservice.ProcessActivityElementType;
import com.enterprise.process.web.service.processservice.ProcessAuditElement;
import com.enterprise.process.web.service.processservice.ProcessAuditElementType;
import com.enterprise.process.web.service.processservice.StartProcessRequest;
import com.enterprise.process.web.service.processservice.StartProcessResponse;
import com.enterprise.process.web.service.processservice.TaskSummaryElement;
import com.enterprise.process.web.service.processservice.TaskUserElement;
import com.enterprise.process.web.service.processservice.WorkOnTaskRequest;
import com.enterprise.process.web.service.processservice.WorkOnTaskResponse;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.enterprise.process.web.service.processservice.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enterprise.process.web.service.processservice.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClaimTaskResponse }
     * 
     */
    public ClaimTaskResponseImpl createClaimTaskResponse() {
        return new ClaimTaskResponseImpl();
    }

    /**
     * Create an instance of {@link WorkOnTaskResponse }
     * 
     */
    public WorkOnTaskResponseImpl createWorkOnTaskResponse() {
        return new WorkOnTaskResponseImpl();
    }

    /**
     * Create an instance of {@link StartProcessResponse }
     * 
     */
    public StartProcessResponseImpl createStartProcessResponse() {
        return new StartProcessResponseImpl();
    }

    /**
     * Create an instance of {@link ClaimTaskRequest }
     * 
     */
    public ClaimTaskRequestImpl createClaimTaskRequest() {
        return new ClaimTaskRequestImpl();
    }

    /**
     * Create an instance of {@link StartProcessRequest }
     * 
     */
    public StartProcessRequestImpl createStartProcessRequest() {
        return new StartProcessRequestImpl();
    }

    /**
     * Create an instance of {@link TaskUserElement }
     * 
     */
    public TaskUserElementImpl createTaskUserElement() {
        return new TaskUserElementImpl();
    }

    /**
     * Create an instance of {@link ProcessAuditElement }
     * 
     */
    public ProcessAuditElementImpl createProcessAuditElement() {
        return new ProcessAuditElementImpl();
    }

    /**
     * Create an instance of {@link WorkOnTaskRequest }
     * 
     */
    public WorkOnTaskRequestImpl createWorkOnTaskRequest() {
        return new WorkOnTaskRequestImpl();
    }

    /**
     * Create an instance of {@link ParameterElement }
     * 
     */
    public ParameterElementImpl createParameterElement() {
        return new ParameterElementImpl();
    }

    /**
     * Create an instance of {@link CompleteTaskRequest }
     * 
     */
    public CompleteTaskRequestImpl createCompleteTaskRequest() {
        return new CompleteTaskRequestImpl();
    }

    /**
     * Create an instance of {@link ProcessAuditElementType }
     * 
     */
    public ProcessAuditElementTypeImpl createProcessAuditElementType() {
        return new ProcessAuditElementTypeImpl();
    }

    /**
     * Create an instance of {@link CompleteTaskResponse }
     * 
     */
    public CompleteTaskResponseImpl createCompleteTaskResponse() {
        return new CompleteTaskResponseImpl();
    }

    /**
     * Create an instance of {@link FetchUserTasksRequest }
     * 
     */
    public FetchUserTasksRequestImpl createFetchUserTasksRequest() {
        return new FetchUserTasksRequestImpl();
    }

    /**
     * Create an instance of {@link FetchUserTasksResponse }
     * 
     */
    public FetchUserTasksResponseImpl createFetchUserTasksResponse() {
        return new FetchUserTasksResponseImpl();
    }

    /**
     * Create an instance of {@link TaskSummaryElement }
     * 
     */
    public TaskSummaryElementImpl createTaskSummaryElement() {
        return new TaskSummaryElementImpl();
    }

    /**
     * Create an instance of {@link ProcessActivityElementType }
     * 
     */
    public ProcessActivityElementTypeImpl createProcessActivityElementType() {
        return new ProcessActivityElementTypeImpl();
    }

}
