//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 05:48:17 PM GMT 
//


package com.enterprise.process.web.service.processservice.impl;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.enterprise.process.web.service.processservice.ParameterElement;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterElement", namespace = "http://com/enterprise/process/web/service/ProcessService", propOrder = {
    "variable",
    "value"
})
public class ParameterElementImpl
    implements Serializable, ParameterElement
{

    private final static long serialVersionUID = 3099325368888314454L;
    @XmlElement(required = true)
    protected String variable;
    @XmlElement(required = true)
    protected String value;

    public String getVariable() {
        return variable;
    }

    public void setVariable(String value) {
        this.variable = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
