//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 05:48:17 PM GMT 
//


package com.enterprise.process.web.service.processservice.impl;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.enterprise.process.web.service.processservice.TaskStatusElement;
import com.enterprise.process.web.service.processservice.TaskSummaryElement;
import com.enterprise.process.web.service.processservice.TaskUserElement;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskSummaryElement", namespace = "http://com/enterprise/process/web/service/ProcessService", propOrder = {
    "id",
    "processInstanceId",
    "name",
    "subject",
    "description",
    "status",
    "priority",
    "skipable",
    "actualOwner",
    "createdBy",
    "createdOn",
    "activationTime",
    "expirationTime",
    "processId",
    "processSessionId",
    "reference",
    "title",
    "firstNames",
    "lastName",
    "fullName"
})
public class TaskSummaryElementImpl
    implements Serializable, TaskSummaryElement
{

    private final static long serialVersionUID = 3099325368888314454L;
    protected Long id;
    protected Long processInstanceId;
    protected String name;
    protected String subject;
    protected String description;
    protected TaskStatusElement status;
    protected BigInteger priority;
    protected Boolean skipable;
    @XmlElement(type = TaskUserElementImpl.class)
    protected TaskUserElementImpl actualOwner;
    @XmlElement(type = TaskUserElementImpl.class)
    protected TaskUserElementImpl createdBy;
    protected String createdOn;
    protected String activationTime;
    protected String expirationTime;
    protected String processId;
    protected BigInteger processSessionId;
    protected String reference;
    protected String title;
    protected String firstNames;
    protected String lastName;
    protected String fullName;

    public Long getId() {
        return id;
    }

    public void setId(Long value) {
        this.id = value;
    }

    public Long getProcessInstanceId() {
        return processInstanceId;
    }

    public void setProcessInstanceId(Long value) {
        this.processInstanceId = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String value) {
        this.subject = value;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        this.description = value;
    }

    public TaskStatusElement getStatus() {
        return status;
    }

    public void setStatus(TaskStatusElement value) {
        this.status = value;
    }

    public BigInteger getPriority() {
        return priority;
    }

    public void setPriority(BigInteger value) {
        this.priority = value;
    }

    public Boolean isSkipable() {
        return skipable;
    }

    public void setSkipable(Boolean value) {
        this.skipable = value;
    }

    public TaskUserElement getActualOwner() {
        return actualOwner;
    }

    public void setActualOwner(TaskUserElement value) {
        this.actualOwner = ((TaskUserElementImpl) value);
    }

    public TaskUserElement getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(TaskUserElement value) {
        this.createdBy = ((TaskUserElementImpl) value);
    }

    public String getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(String value) {
        this.createdOn = value;
    }

    public String getActivationTime() {
        return activationTime;
    }

    public void setActivationTime(String value) {
        this.activationTime = value;
    }

    public String getExpirationTime() {
        return expirationTime;
    }

    public void setExpirationTime(String value) {
        this.expirationTime = value;
    }

    public String getProcessId() {
        return processId;
    }

    public void setProcessId(String value) {
        this.processId = value;
    }

    public BigInteger getProcessSessionId() {
        return processSessionId;
    }

    public void setProcessSessionId(BigInteger value) {
        this.processSessionId = value;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String value) {
        this.reference = value;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String value) {
        this.title = value;
    }

    public String getFirstNames() {
        return firstNames;
    }

    public void setFirstNames(String value) {
        this.firstNames = value;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String value) {
        this.lastName = value;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String value) {
        this.fullName = value;
    }

}
