//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 05:48:17 PM GMT 
//


package com.enterprise.process.web.service.processservice.impl;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.enterprise.process.web.service.processservice.ProcessActivityElementType;
import com.enterprise.process.web.service.processservice.ProcessAuditElementType;
import com.enterprise.web.service.globaldictionary.DateElement;
import com.enterprise.web.service.globaldictionary.impl.DateElementImpl;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessAuditElementType", namespace = "http://com/enterprise/process/web/service/ProcessService", propOrder = {
    "startDate",
    "endDate",
    "activities"
})
public class ProcessAuditElementTypeImpl
    implements Serializable, ProcessAuditElementType
{

    private final static long serialVersionUID = 3099325368888314454L;
    @XmlElement(required = true, type = DateElementImpl.class)
    protected DateElementImpl startDate;
    @XmlElement(type = DateElementImpl.class)
    protected DateElementImpl endDate;
    @XmlElement(type = ProcessActivityElementTypeImpl.class)
    protected List<ProcessActivityElementType> activities;

    public DateElement getStartDate() {
        return startDate;
    }

    public void setStartDate(DateElement value) {
        this.startDate = ((DateElementImpl) value);
    }

    public DateElement getEndDate() {
        return endDate;
    }

    public void setEndDate(DateElement value) {
        this.endDate = ((DateElementImpl) value);
    }

    public List<ProcessActivityElementType> getActivities() {
        if (activities == null) {
            activities = new ArrayList<ProcessActivityElementType>();
        }
        return this.activities;
    }

}
