//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 05:48:17 PM GMT 
//


package com.enterprise.process.web.service.processservice.impl;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.enterprise.process.web.service.processservice.ProcessActivityElementType;
import com.enterprise.web.service.globaldictionary.DateElement;
import com.enterprise.web.service.globaldictionary.StatusTypesElement;
import com.enterprise.web.service.globaldictionary.impl.DateElementImpl;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessActivityElementType", namespace = "http://com/enterprise/process/web/service/ProcessService", propOrder = {
    "taskName",
    "status",
    "owner",
    "timestamp",
    "comments"
})
public class ProcessActivityElementTypeImpl
    implements Serializable, ProcessActivityElementType
{

    private final static long serialVersionUID = 3099325368888314454L;
    @XmlElement(required = true)
    protected String taskName;
    @XmlElement(required = true)
    protected StatusTypesElement status;
    @XmlElement(required = true)
    protected String owner;
    @XmlElement(required = true, type = DateElementImpl.class)
    protected DateElementImpl timestamp;
    protected String comments;

    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String value) {
        this.taskName = value;
    }

    public StatusTypesElement getStatus() {
        return status;
    }

    public void setStatus(StatusTypesElement value) {
        this.status = value;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String value) {
        this.owner = value;
    }

    public DateElement getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(DateElement value) {
        this.timestamp = ((DateElementImpl) value);
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String value) {
        this.comments = value;
    }

}
