//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 05:48:17 PM GMT 
//


package com.enterprise.web.service.globaldictionary;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusTypesElement.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StatusTypesElement">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SUCCESSFUL"/>
 *     &lt;enumeration value="FAILED"/>
 *     &lt;enumeration value="RESERVED"/>
 *     &lt;enumeration value="INPROGRESS"/>
 *     &lt;enumeration value="COMPLETED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StatusTypesElement", namespace = "http://com/enterprise/web/service/GlobalDictionary")
@XmlEnum
public enum StatusTypesElement {

    SUCCESSFUL,
    FAILED,
    RESERVED,
    INPROGRESS,
    COMPLETED;

    public String value() {
        return name();
    }

    public static StatusTypesElement fromValue(String v) {
        return valueOf(v);
    }

}
