//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.25 at 07:16:08 AM CAT 
//


package com.enterprise.common.xsd.webelementcomplextypes;

import javax.xml.bind.annotation.XmlRegistry;
import com.enterprise.common.xsd.webelementcomplextypes.impl.CellphoneNumberInputElementImpl;
import com.enterprise.common.xsd.webelementcomplextypes.impl.MandatoryEmailInputElementImpl;
import com.enterprise.common.xsd.webelementcomplextypes.impl.MandatoryNumberElementImpl;
import com.enterprise.common.xsd.webelementcomplextypes.impl.MandatoryValueElementImpl;
import com.enterprise.common.xsd.webelementcomplextypes.impl.PasswordInputElementImpl;
import com.enterprise.common.xsd.webelementcomplextypes.impl.UsernameInputElementImpl;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.enterprise.common.xsd.webelementcomplextypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static Void _useJAXBProperties = null;

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enterprise.common.xsd.webelementcomplextypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MandatoryEmailInputElement }
     * 
     */
    public MandatoryEmailInputElement createMandatoryEmailInputElement() {
        return new MandatoryEmailInputElementImpl();
    }

    /**
     * Create an instance of {@link UsernameInputElement }
     * 
     */
    public UsernameInputElement createUsernameInputElement() {
        return new UsernameInputElementImpl();
    }

    /**
     * Create an instance of {@link MandatoryNumberElement }
     * 
     */
    public MandatoryNumberElement createMandatoryNumberElement() {
        return new MandatoryNumberElementImpl();
    }

    /**
     * Create an instance of {@link CellphoneNumberInputElement }
     * 
     */
    public CellphoneNumberInputElement createCellphoneNumberInputElement() {
        return new CellphoneNumberInputElementImpl();
    }

    /**
     * Create an instance of {@link MandatoryValueElement }
     * 
     */
    public MandatoryValueElement createMandatoryValueElement() {
        return new MandatoryValueElementImpl();
    }

    /**
     * Create an instance of {@link PasswordInputElement }
     * 
     */
    public PasswordInputElement createPasswordInputElement() {
        return new PasswordInputElementImpl();
    }

}
