//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 05:48:17 PM GMT 
//


package com.enterprise.process.web.service.processservice;

import javax.xml.bind.annotation.XmlRegistry;
import com.enterprise.process.web.service.processservice.impl.ClaimTaskRequestImpl;
import com.enterprise.process.web.service.processservice.impl.ClaimTaskResponseImpl;
import com.enterprise.process.web.service.processservice.impl.CompleteTaskRequestImpl;
import com.enterprise.process.web.service.processservice.impl.CompleteTaskResponseImpl;
import com.enterprise.process.web.service.processservice.impl.FetchUserTasksRequestImpl;
import com.enterprise.process.web.service.processservice.impl.FetchUserTasksResponseImpl;
import com.enterprise.process.web.service.processservice.impl.ParameterElementImpl;
import com.enterprise.process.web.service.processservice.impl.ProcessActivityElementTypeImpl;
import com.enterprise.process.web.service.processservice.impl.ProcessAuditElementImpl;
import com.enterprise.process.web.service.processservice.impl.ProcessAuditElementTypeImpl;
import com.enterprise.process.web.service.processservice.impl.StartProcessRequestImpl;
import com.enterprise.process.web.service.processservice.impl.StartProcessResponseImpl;
import com.enterprise.process.web.service.processservice.impl.TaskSummaryElementImpl;
import com.enterprise.process.web.service.processservice.impl.TaskUserElementImpl;
import com.enterprise.process.web.service.processservice.impl.WorkOnTaskRequestImpl;
import com.enterprise.process.web.service.processservice.impl.WorkOnTaskResponseImpl;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.enterprise.process.web.service.processservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static Void _useJAXBProperties = null;

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enterprise.process.web.service.processservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClaimTaskResponse }
     * 
     */
    public ClaimTaskResponse createClaimTaskResponse() {
        return new ClaimTaskResponseImpl();
    }

    /**
     * Create an instance of {@link WorkOnTaskResponse }
     * 
     */
    public WorkOnTaskResponse createWorkOnTaskResponse() {
        return new WorkOnTaskResponseImpl();
    }

    /**
     * Create an instance of {@link StartProcessResponse }
     * 
     */
    public StartProcessResponse createStartProcessResponse() {
        return new StartProcessResponseImpl();
    }

    /**
     * Create an instance of {@link ClaimTaskRequest }
     * 
     */
    public ClaimTaskRequest createClaimTaskRequest() {
        return new ClaimTaskRequestImpl();
    }

    /**
     * Create an instance of {@link StartProcessRequest }
     * 
     */
    public StartProcessRequest createStartProcessRequest() {
        return new StartProcessRequestImpl();
    }

    /**
     * Create an instance of {@link TaskUserElement }
     * 
     */
    public TaskUserElement createTaskUserElement() {
        return new TaskUserElementImpl();
    }

    /**
     * Create an instance of {@link ProcessAuditElement }
     * 
     */
    public ProcessAuditElement createProcessAuditElement() {
        return new ProcessAuditElementImpl();
    }

    /**
     * Create an instance of {@link WorkOnTaskRequest }
     * 
     */
    public WorkOnTaskRequest createWorkOnTaskRequest() {
        return new WorkOnTaskRequestImpl();
    }

    /**
     * Create an instance of {@link ParameterElement }
     * 
     */
    public ParameterElement createParameterElement() {
        return new ParameterElementImpl();
    }

    /**
     * Create an instance of {@link CompleteTaskRequest }
     * 
     */
    public CompleteTaskRequest createCompleteTaskRequest() {
        return new CompleteTaskRequestImpl();
    }

    /**
     * Create an instance of {@link ProcessAuditElementType }
     * 
     */
    public ProcessAuditElementType createProcessAuditElementType() {
        return new ProcessAuditElementTypeImpl();
    }

    /**
     * Create an instance of {@link CompleteTaskResponse }
     * 
     */
    public CompleteTaskResponse createCompleteTaskResponse() {
        return new CompleteTaskResponseImpl();
    }

    /**
     * Create an instance of {@link FetchUserTasksRequest }
     * 
     */
    public FetchUserTasksRequest createFetchUserTasksRequest() {
        return new FetchUserTasksRequestImpl();
    }

    /**
     * Create an instance of {@link FetchUserTasksResponse }
     * 
     */
    public FetchUserTasksResponse createFetchUserTasksResponse() {
        return new FetchUserTasksResponseImpl();
    }

    /**
     * Create an instance of {@link TaskSummaryElement }
     * 
     */
    public TaskSummaryElement createTaskSummaryElement() {
        return new TaskSummaryElementImpl();
    }

    /**
     * Create an instance of {@link ProcessActivityElementType }
     * 
     */
    public ProcessActivityElementType createProcessActivityElementType() {
        return new ProcessActivityElementTypeImpl();
    }

}
