//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 05:48:17 PM GMT 
//


package com.enterprise.process.web.service.processservice;

import java.util.List;
import com.enterprise.common.xsd.Element;
import com.enterprise.web.service.globaldictionary.DateElement;


/**
 * <p>Java class for ProcessAuditElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessAuditElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startDate" type="{http://com/enterprise/web/service/GlobalDictionary}DateElement"/>
 *         &lt;element name="endDate" type="{http://com/enterprise/web/service/GlobalDictionary}DateElement" minOccurs="0"/>
 *         &lt;element name="activities" type="{http://com/enterprise/process/web/service/ProcessService}ProcessActivityElementType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface ProcessAuditElementType
    extends Element
{


    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateElement }
     *     
     */
    DateElement getStartDate();

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateElement }
     *     
     */
    void setStartDate(DateElement value);

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateElement }
     *     
     */
    DateElement getEndDate();

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateElement }
     *     
     */
    void setEndDate(DateElement value);

    /**
     * Gets the value of the activities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessActivityElementType }
     * 
     * 
     */
    List<ProcessActivityElementType> getActivities();

}
