//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 05:48:17 PM GMT 
//


package com.enterprise.process.web.service.processservice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaskStatusElement.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TaskStatusElement">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Created"/>
 *     &lt;enumeration value="Ready"/>
 *     &lt;enumeration value="Reserved"/>
 *     &lt;enumeration value="InProgress"/>
 *     &lt;enumeration value="Suspended"/>
 *     &lt;enumeration value="Completed"/>
 *     &lt;enumeration value="Failed"/>
 *     &lt;enumeration value="Error"/>
 *     &lt;enumeration value="Exited"/>
 *     &lt;enumeration value="Obsolete"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TaskStatusElement", namespace = "http://com/enterprise/process/web/service/ProcessService")
@XmlEnum
public enum TaskStatusElement {

    @XmlEnumValue("Created")
    CREATED("Created"),
    @XmlEnumValue("Ready")
    READY("Ready"),
    @XmlEnumValue("Reserved")
    RESERVED("Reserved"),
    @XmlEnumValue("InProgress")
    IN_PROGRESS("InProgress"),
    @XmlEnumValue("Suspended")
    SUSPENDED("Suspended"),
    @XmlEnumValue("Completed")
    COMPLETED("Completed"),
    @XmlEnumValue("Failed")
    FAILED("Failed"),
    @XmlEnumValue("Error")
    ERROR("Error"),
    @XmlEnumValue("Exited")
    EXITED("Exited"),
    @XmlEnumValue("Obsolete")
    OBSOLETE("Obsolete");
    private final String value;

    TaskStatusElement(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TaskStatusElement fromValue(String v) {
        for (TaskStatusElement c: TaskStatusElement.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
