//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.25 at 07:16:08 AM CAT 
//


package com.enterprise.common.xsd.webelementcomplextypes.impl;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.enterprise.common.xsd.webelementcomplextypes.MandatoryValueElement;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MandatoryValueElement", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes", propOrder = {
    "id",
    "name",
    "type",
    "style",
    "styleClass",
    "styleClassAlt",
    "title",
    "valid",
    "error",
    "value",
    "attributes",
    "disabled",
    "readonly"
})
@XmlRootElement(name = "MandatoryValueElement", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
public class MandatoryValueElementImpl
    implements Serializable, MandatoryValueElement
{

    private final static long serialVersionUID = 3099325368888314454L;
    @XmlElement(name = "Id", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String id;
    @XmlElement(name = "Name", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String name;
    @XmlElement(name = "Type", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String type;
    @XmlElement(name = "Style", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String style;
    @XmlElement(name = "StyleClass", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String styleClass;
    @XmlElement(name = "StyleClassAlt", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String styleClassAlt;
    @XmlElement(name = "Title", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String title;
    @XmlElement(name = "Valid", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected Boolean valid;
    @XmlElement(name = "Error", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String error;
    @XmlElement(name = "Value", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes", required = true)
    protected String value;
    @XmlElement(name = "Attributes", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String attributes;
    @XmlElement(name = "Disabled", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String disabled;
    @XmlElement(name = "Readonly", namespace = "http://xsd.common.enterprise.com/WebElementComplexTypes")
    protected String readonly;

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getType() {
        return type;
    }

    public void setType(String value) {
        this.type = value;
    }

    public String getStyle() {
        return style;
    }

    public void setStyle(String value) {
        this.style = value;
    }

    public String getStyleClass() {
        return styleClass;
    }

    public void setStyleClass(String value) {
        this.styleClass = value;
    }

    public String getStyleClassAlt() {
        return styleClassAlt;
    }

    public void setStyleClassAlt(String value) {
        this.styleClassAlt = value;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String value) {
        this.title = value;
    }

    public Boolean isValid() {
        return valid;
    }

    public void setValid(Boolean value) {
        this.valid = value;
    }

    public String getError() {
        return error;
    }

    public void setError(String value) {
        this.error = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getAttributes() {
        return attributes;
    }

    public void setAttributes(String value) {
        this.attributes = value;
    }

    public String getDisabled() {
        return disabled;
    }

    public void setDisabled(String value) {
        this.disabled = value;
    }

    public String getReadonly() {
        return readonly;
    }

    public void setReadonly(String value) {
        this.readonly = value;
    }

}
