//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.25 at 07:16:08 AM CAT 
//


package com.enterprise.common.xsd.webelementcomplextypes.impl;

import javax.xml.bind.annotation.XmlRegistry;
import com.enterprise.common.xsd.webelementcomplextypes.CellphoneNumberInputElement;
import com.enterprise.common.xsd.webelementcomplextypes.MandatoryEmailInputElement;
import com.enterprise.common.xsd.webelementcomplextypes.MandatoryNumberElement;
import com.enterprise.common.xsd.webelementcomplextypes.MandatoryValueElement;
import com.enterprise.common.xsd.webelementcomplextypes.PasswordInputElement;
import com.enterprise.common.xsd.webelementcomplextypes.UsernameInputElement;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.enterprise.common.xsd.webelementcomplextypes.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enterprise.common.xsd.webelementcomplextypes.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MandatoryEmailInputElement }
     * 
     */
    public MandatoryEmailInputElementImpl createMandatoryEmailInputElement() {
        return new MandatoryEmailInputElementImpl();
    }

    /**
     * Create an instance of {@link UsernameInputElement }
     * 
     */
    public UsernameInputElementImpl createUsernameInputElement() {
        return new UsernameInputElementImpl();
    }

    /**
     * Create an instance of {@link MandatoryNumberElement }
     * 
     */
    public MandatoryNumberElementImpl createMandatoryNumberElement() {
        return new MandatoryNumberElementImpl();
    }

    /**
     * Create an instance of {@link CellphoneNumberInputElement }
     * 
     */
    public CellphoneNumberInputElementImpl createCellphoneNumberInputElement() {
        return new CellphoneNumberInputElementImpl();
    }

    /**
     * Create an instance of {@link MandatoryValueElement }
     * 
     */
    public MandatoryValueElementImpl createMandatoryValueElement() {
        return new MandatoryValueElementImpl();
    }

    /**
     * Create an instance of {@link PasswordInputElement }
     * 
     */
    public PasswordInputElementImpl createPasswordInputElement() {
        return new PasswordInputElementImpl();
    }

}
